version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
