version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/inventory_db
      JWT_SECRET: supersecret
    depends_on:
      - postgres
    ports:
      - '5000:5000'

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    depends_on:
      - server
    ports:
      - '3000:3000'

volumes:
  pgdata:
